import styles from '../../assets/styles/Home.module.css';
import { useRouter } from 'next/router';
import Head from 'next/head';
import MainLayout from '../../layout/main-layout';

function ProductPage() {
  const router = useRouter();
  return (
    <MainLayout>
      <Head>
        <title>Product page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className={styles.title}>Product page {router.query.productId}</h1>
    </MainLayout>
  );
}

export default ProductPage;
