import Head from 'next/head';
import Image from 'next/image';
import styles from '../../assets/styles/Home.module.css';
import MainLayout from '../../layout/main-layout';

function ProductsPage() {
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainLayout>
        <h1 className={styles.title}>Products page!</h1>
      </MainLayout>
    </>
  );
}

export default ProductsPage;
